"""empty message

Revision ID: 026c39d61fa2
Revises: f76b389307e6
Create Date: 2023-05-22 17:05:55.740327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026c39d61fa2'
down_revision = 'f76b389307e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
