"""initial1

Revision ID: 05decfbef3c7
Revises: f4888cf7f4e9
Create Date: 2023-05-19 03:06:10.414683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05decfbef3c7'
down_revision = 'f4888cf7f4e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
